rherrainz/alkemy-library

src/controllers/book.controller.js, src/routes/book.route.js, src/services/book.service.js
Se implementa el endpoint solicitado en el ticket además de su respectivo método en el  controller y service
=> [T4S3-41] Implementación endpoint DELETE byId de Libros

src/controllers/user.controller.js, src/routes/user.route.js, src/services/user.service.js
Termine de implementar el controlador getById de Users agregando la conexión con el service y repository
=> [T4S3-32] Implementación endpoint GET byId de Usuarios

src/controllers/book.controller.js, src/routes/book.route.js
Implementación del controlador getAll de Books
=> [T4S3-37] Implementación endpoint GET all de Usuarios

src/controllers/author.controller.js, src/repositories/author.repository.js, src/routes/author.route.js, src/services/author.service.js
Modificación de author.route.js y author.repository. Creación de author.controller.js y author.service.js.
Implementación de métodos getAll, getByAuthorId, update y remove.
=> [T4S3-34] Implementación de Endpoint para la gestión de datos de autores

src/controllers/user.controller.js, src/routes/user.route.js, src/services/user.service.js
=> Implementación endpoint GET all de Usuarios

src/controllers/author.controller.js, src/routes/author.route.js, src/services/author.service.js
Implementación de Endpoint POST para la creación de autores.
=> T4S3-42 - Implementación de Endpoint POST /autores

src/app.js, src/constants/role.constants.js, src/controllers/authentication.controller.js, src/db/index.db.js, src/db/models/role.model.js, src/db/models/user.model.js, src/middlewares/authorization.middleware.js, src/routes/user.route.js, src/services/authentication.service.js, src/services/user.service.js
Refactorizar el middleware de autenticación, implementando la constante roles
- Se eliminó la dependencia de la tabla de roles en el middleware de autenticación.
- Se agregó un nuevo campo 'rol' a la tabla Usuario para almacenar roles de usuario.
- Corregidas las llamadas y verificación de roles en el middleware de autenticación.
- Se introdujo un 'rol' constante para las comparaciones de roles.
=> [T4S3-43] [T4S3-30] Refactorización del middleware de autenticación (Seguridad de Usuario)

src/controllers/user.controller.js, src/middlewares/authorization.middleware.js, src/routes/user.route.js, src/services/user.service.js
=> [T4S3-23] Implementación del endpoint DELETE  users/:id

src/controllers/loan.controller.js, src/repositories/loan.repository.js, src/routes/index.route.js, src/routes/loan.route.js, src/services/loan.service.js
=> [T4S3-47] Implementación del controller para préstamo de Libros

src/controllers/review.controller.js, src/db/models/book.model.js, src/db/models/review.model.js, src/repositories/review.repository.js, src/routes/index.route.js, src/routes/review.route.js, src/services/review.service.js
review.route.js
review.controller.js
review.repository.js
=> [T4S3-68] [T4S3-69] Implementación de reviews de libros.

src/app.js, src/controllers/book.controller.js, src/controllers/loan.controller.js, src/repositories/book.repository.js, src/routes/book.route.js, src/routes/loan.route.js, src/services/book.service.js
* Book Router
*  Book Controller 
* Book Repo
=> [T4S3-45] Implementación del endpoint book/loan

.gitignore, src/controllers/authentication.controller.js, src/controllers/loan.controller.js, src/db/models/user.model.js, src/log/logger.log.js, src/repositories/loan.repository.js, src/routes/loan.route.js
logger.log.js
Implementación del registro de eventos en inicio de sesión
Implementación del registro de eventos en prestamos
=> [T4S3-73] Monitorear la actividad en la aplicación.

src/controllers/user.controller.js, src/db/index.db.js, src/repositories/book.repository.js, src/repositories/user.repository.js, src/routes/user.route.js, src/services/book.service.js, src/services/user.service.js
* Se hace uso de parámetros en la query para realizar la búsqueda en la base de datos debido a la escalabilidad
* Se implementa el service, controlador y ruta necesaria
=> [T4S3-53] Implementación del endpoint get user/params (Filtro de búsqueda)

package-lock.json, package.json, src/app.js, src/controllers/book.controller.js, src/middlewares/authorization.middleware.js, src/middlewares/schemas/index.schema.js, src/middlewares/schemas/loan.schema.js, src/realtime/notifiy.realtime.js, src/realtime/socket.realtime.js, src/repositories/book.repository.js, src/routes/book.route.js, src/routes/user.route.js, src/services/book.service.js
- Se implementa un web socket utilizando la librería 'socket.io'
- Se crea una clase padre que contendrá la configuración principal del ws para utilizarlo a lo largo del ciclo de vida de la api.
- Se crea una clase especializada que heredará de la clase principal y generará una sobrecarga de métodos según sea necesario.
- Se genera una instancia de 'io' a nivel global de la api con el fin de implementarlo en distintos lugares del codigo.
- Se refactoriza en Book Repository el método 'returnBook' con el fin de obtener el título y edición del libro que se quiere devolver.
- Se refactoriza en Book Service el método returnBook para implementar la emisión del evento 'notification' e informar al cliente que libro se devolvió.
- Se utiliza postman como servidor Front para las pruebas.
=> [T4S3-66] Implementación del Web Socket

package-lock.json, package.json, src/app.js, src/controllers/chat.controller.js, src/public/chat.handlebars, src/realtime/chat.realtime.js, src/realtime/notifiy.realtime.js, src/routes/chat.route.js, src/routes/index.route.js
IMPORTANTE: Por el momento, el acceso al chat se realiza proporcionando 'id, firstName y lastName' a través de query params. Esto se debe a que, en el navegador, no es posible utilizar directamente el token de autenticación. En un entorno de producción, normalmente utilizaría los datos del usuario obtenidos a través del middleware con req.user.
=> [T4S3-71] [T4S3-72] Sistema de chat en tiempo real

package-lock.json, package.json, src/app.js, src/controllers/book.controller.js, src/controllers/loan.controller.js, src/db/models/loan.model.js, src/messages/messages.js, src/repositories/book.repository.js, src/repositories/loan.repository.js, src/routes/book.route.js, src/services/book.service.js, src/services/loan.service.js, src/utils/cron.util.js
=> [T4S3-67] Implementación de búsqueda avanzada por titulo, genero y autor con paginación

package.json, src/app.js, src/security/backup.security.js, src/tasks/backup.task.js
- Se crea un nuevo módulo llamado 'tasks' que contendrá la tarea automatizada.
- Para evitar que la tarea se llame automáticamente al importar 'backup.security.js' se modifica la llamada a la función 'backup()' en el script:
- Se crea la tarea automatizada en 'tasks' utilizando node-cron y se configura para su ejecución todos los días a la media noche:
- Finalmente se modifica el script 'backup' en package.json asignandole un argumento:
=> [T4S3-79] Implementación de backup automatizado

src/db/models/loan.model.js
=> Modificando el modelo de prestamos

src/messages/messages.js, src/repositories/loan.repository.js, src/services/loan.service.js
=> Resolviendo pequeños errores

package-lock.json, package.json, src/app.js
Se agrega el middleware compression para comprimir las respuestas del servidor y reducir el ancho de banda.
=> [T4S3-100] Diseñar y desarrollar un middleware de compresión de respuestas.

package-lock.json, package.json, src/app.js
Se agregan middlewares para proteger ataques XSS, CSRF y encabezados seguros.
helmet para encabezados seguros
xss para XSS
y csurf para CSRF
=> [T4S3-102] Implementar el manejo de errores para proteger la aplicación de amenazas como ataques de inyección de SQL, XSS y CSRF.

src/controllers/userActivity.controller.js, src/repositories/event.repository.js, src/routes/index.route.js, src/routes/userActivity.route.js, src/services/event.service.js, src/services/loan.service.js
Se agregaron dos rutas junto con sus controladores y servicios:
userActivity/loans/:id retorna el historial de préstamos del usuario
userActivity/events/:id retorna el historial de eventos del usuario
ambas puden ser accedidas solo por un admin
El servicio llama a los repositorios de eventos y de préstamos para ahorrar código.
=> [T4S3-65] Funcionalidad para generar reportes de actividad de los usuarios en la aplicación

src/controllers/loan.controller.js, src/controllers/user.controller.js, src/docs/swagger.docs.yaml, src/services/loan.service.js
Se instalaron las dependencias swagger-jsdoc, swagger-ui-express y yamljs que permiten separar la documentación en un archivo YAML aparte y para poder correrlo en el navegador.
Se agrega la nueva ruta /api-docs donde va a estar la documentación
Se implemento la documentación para auth, users, y loans
=> [T4S3-103] [T4S3-104] Implementación de documentación con Swagger
